format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuri is "character"
success_symbol = "[λ](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[λ](bold red)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[git_branch]
symbol = ' '
